source 'http://rubygems.org'
ruby '2.4.0'

gem 'activesupport', :path => File.join(File.dirname(__FILE__), '/vendor/gems/activesupport-4.2.7.1')
gem 'bencode'
gem 'deluge-rpc', :git => 'https://github.com/raphyduck/deluge-rpc.git'
gem 'fuzzy-string-match'
gem 'httparty'
gem 'imdb', :git => 'https://github.com/raphyduck/imdb.git'
gem 'net-ssh'
gem 'nokogiri'
gem 'rsync'
gem 'sqlite3'
gem 'sys-filesystem'
gem 't411', :git => 'https://github.com/raphyduck/t411.git'
gem 'trakt', :git => 'https://github.com/raphyduck/trakt.git'
gem 'tvmaze', :git => 'https://github.com/raphyduck/tvmaze.git'
gem 'xbmc-client', :git => 'https://github.com/raphyduck/xbmc-client.git'