source 'http://rubygems.org'
ruby '2.4.0'

gem 'activesupport'
gem 'bencode'
gem 'deluge-rpc', :git => 'https://github.com/raphyduck/deluge-rpc.git'
gem 'fuzzy-string-match'
gem 'httparty'
gem 'imdb', :git => 'https://github.com/raphyduck/imdb.git'
gem 'net-ssh'
gem 'nokogiri'
gem 'sqlite3'
gem 't411', :git => 'https://github.com/raphyduck/t411.git'
gem 'trakt', :git => 'https://github.com/raphyduck/trakt.git'
gem 'tvmaze', :git => 'https://github.com/raphyduck/tvmaze.git'