source 'http://rubygems.org'
ruby '2.4.0'

gem 'activesupport'
gem 'deluge-rpc'
gem 'fuzzy-string-match'
gem 'imdb', '~> 0.8'
gem 'net-ssh'
gem 't411', :git => 'https://github.com/raphyduck/t411.git'
gem 'nokogiri'
gem 'httparty'